# Hey ML pipeline! Here’s the plan:
#1.Store all work in a big folder called artifacts/
#2.First task: get the dataset from this GitHub zip URL
#3.Save the zip file in artifacts/data_ingestion/
#4.Then unzip it there so we can use the raw data."
artifacts_root: artifacts
data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Bavan-M/Branching_tutorial/raw/refs/heads/main/wine_quality_dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

#1.All validation outputs go into artifacts/data_validation/.
#2.The validated dataset (e.g., winequality-red.csv) will be stored in artifacts/data_validation/winequality-red.csv.
#3.A status.txt file in artifacts/data_validation/ will log validation results (e.g., pass/fail).
data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt

#1.All transformation outputs go into artifacts/data_transformation/.
#2.Use the validated dataset from artifacts/data_ingestion/winequality-red.csv.
data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv

#1.All training outputs go into artifacts/model_trainer/
#2.Uses preprocessed training data from artifacts/data_transformation/train.csv
#3.Uses test data from artifacts/data_transformation/test.csv
#4.Trained model will be saved as model.joblib in the root directory
model_trianer:
  root_dir: artifacts/model_trianer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

#1.All evaluation outputs go into artifacts/model_evaluation/
#2.Test data from artifacts/data_transformation/test.csv
#3.Trained model from artifacts/model_trainer/model.joblib
#4.Evaluation metrics saved as JSON at artifacts/model_evaluation/metrics.json
model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trianer/model.joblib
  matric_file_name: artifacts/model_evaluation/metrics.json